// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(YoneticiModuluContext))]
    [Migration("20230205135523_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityLayer.AlbumBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlbumId")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlbumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AlbümAdı")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("date")
                        .HasColumnName("ÇıkışTarihi")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnOrder(5);

                    b.Property<int?>("IndirimOrani")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("İndirimOranı")
                        .HasColumnOrder(6);

                    b.Property<string>("SanatciveyaGrup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SanatçıveyaGrup")
                        .HasColumnOrder(3);

                    b.Property<bool>("SatisiVarMi")
                        .HasColumnType("bit")
                        .HasColumnName("SatisiVarMi")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.ToTable("AlbümBilgileri", (string)null);
                });

            modelBuilder.Entity("EntityLayer.YoneticiGirisBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YöneticiId")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("KullanıcıAdı")
                        .HasColumnOrder(2);

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Şifre")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Yöneticiler", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
